---
Deliverable 1: "Linear Regression Analysis"
output: Determine variables that predict mpg
---


```{r}
# Import libraries
library(tidyverse)
```

```{r}
# Import Data
car_data <- read.csv('MechaCar_mpg.csv')
```

```{r}
# Linear Regression
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=car_data))
```


---
Deliverable 2: "Summary Statistics of Suspension Coils"
output: Compare the PSI of the suspension coils between manufacturing lots
---

```{r}
# Import Data
coil_data <- read.csv('Suspension_Coil.csv')
```

```{r}
# Summary DataFrame
total_summary = coil_data %>%
  summarize(mean(PSI), median(PSI), var(PSI), sd(PSI))

lot_summary = coil_data %>%
  group_by(Manufacturing_Lot) %>%
  summarize(mean(PSI), median(PSI), var(PSI), sd(PSI))

```


---
Deliverable 3: "T-Test on Suspension Coils"
output: Use t-tests to determine if different lots are statistically different
---


```{r}

# T Test for all lots
t.test(coil_data$PSI, mu=1500)
# T Test for each lots
t.test(subset(coil_data, Manufacturing_Lot == 'Lot1')$PSI, mu=1500)
t.test(subset(coil_data, Manufacturing_Lot == 'Lot2')$PSI, mu=1500)
t.test(subset(coil_data, Manufacturing_Lot == 'Lot3')$PSI, mu=1500)
```
